name: Appimage JDownloader2
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 7 1/7 * *"
  workflow_dispatch: {}

jobs:
  build:
    name: "Build AppImage (x86_64)"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

    - name: Make AppImage
      run: chmod +x ./jdownloader2-appimage.sh && ./jdownloader2-appimage.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: AppImage-x86_64
        path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: AppImage-*
          merge-multiple: true

      - name: Read version information
        run: |
          VERSION=$(cat dist/version)
          echo "VERSION=$VERSION" >> "${GITHUB_ENV}"
          TAG=$(printf '%s' "$VERSION" | cut -d' ' -f2)
          if [ -z "$TAG" ]; then
            TAG=$(printf '%s' "$VERSION" | tr ' ' '_')
          fi
          echo "TAG=$TAG" >> "${GITHUB_ENV}"
          echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "${{ env.VERSION }}"
          tag_name: "${{ env.TAG }}@${{ env.DATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            *.AppImage*
